name = "MultiResponseVarianceComponentModels"
uuid = "95bd6349-d788-4b5f-978d-e543c2eb4d7d"
authors = ["Hua Zhou <huazhou@ucla.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
