name = "MultiResponseVarianceComponentModels"
uuid = "95bd6349-d788-4b5f-978d-e543c2eb4d7d"
authors = ["Hua Zhou <huazhou@ucla.edu> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
